### ISSUE TITLE
Check the checksum of the downloaded file

### ISSUE THREAD

**Issue by kevinpetit** [jfh6/TCoS-Reborn-Launcher#2]
In order to be sure that the file is complete and not corrupt, perform a checksum of the file.

On the server, in the latest.json file or updates.json file, a checksum will be provided per file, to make sure that a download is valid.

It's a md5 checksum.

Example of this:

{
"version": "1.1.0.4",
"file": "latest.zip",
"checksum": "711cc80badf9def2a566cff74a9daad0"
}

https://files.spellborn.org/latest.json

**Comment by jfh6** [comment]
This item has been addressed.
